# Generated by Django 3.1.2 on 2021-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('contact', models.TextField()),
            ],
        ),
    ]
